{
 "title": "Anubis default dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "anubis_challenges_validated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "anubis_challenges_validated{job=\"anubis\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "anubis_policy_results",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "anubis_policy_results{job=\"anubis\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "anubis_challenges_issued",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "anubis_challenges_issued{job=\"anubis\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "anubis_proxied_requests_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "anubis_proxied_requests_total{job=\"anubis\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}